project_id = "oalfgwkzjwmfkaxuomqm"

[functions.extract-historical]
verify_jwt = false

[functions.generate-assumptions]
verify_jwt = false

[functions.summarize-document]
verify_jwt = false

[functions.suggest-folder]
verify_jwt = false
